# Generated by Django 5.0.3 on 2024-04-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_core_book_title_119b07_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('no_of_books_published', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_author_name_fca240_idx')],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='core.author'),
        ),
    ]
